source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.1'
gem 'puma'

# Use sqlite3 as the database for Active Record
gem 'pg'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.0'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'
gem 'haml-rails'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
gem 'react-rails', '~> 0.8.0.0'
gem 'showdown-rails'
gem "twitter-bootstrap-rails"
gem 'bootstrap-modal-rails'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
#gem 'turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.2'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

# Use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.1.2'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]

gem 'configus'
gem 'minitest-rails'

group :test do
  gem 'coveralls', require: false
  gem 'simplecov', :require => false
  # gem 'ruby-prof'
  gem "rake"
  gem 'ci_reporter'
  gem 'mocha', require: false
  gem 'spring'
  gem "spring-commands-testunit", require: false

  gem 'tconsole'
  gem 'launchy'
end

group :development do
  # gem 'meta_request'
  gem 'vendorer'
  gem 'unicorn'
  gem 'quiet_assets'
  gem 'pre-commit'
  gem 'pry-rails'
  gem 'capistrano', '~> 2.5.x'
  gem 'capistrano-ext'
  gem 'capistrano-rbenv'
  #gem 'capistrano-bundler'
  gem 'rvm-capistrano'
  gem 'annotate'
  # gem 'bullet'
end


